name: 'Splice Bot'
description: 'Extract portions of a PR and create new focused PRs from review comments'
author: 'Your Name'

branding:
  icon: 'git-pull-request'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  on-merge:
    description: 'Actions to take when a spliced PR is merged. Comma-separated list of: comment, label. Default: comment,label'
    required: false
    default: 'comment,label'

runs:
  using: 'node20'
  main: 'dist/index.js'
